### ISSUE TITLE
Missing option to disable email submitting to EFF

### ISSUE THREAD

**Issue by jpxd** [neilkuan/cdk-certbot-dns-route53#101]
Hi, thanks for this library, which exactly fits my use case!
I don't want to submit my letsencrypt e-mail address to the EFF though.
Can you please remove the `--eff-email` part from the certbot command or add a CDK option to disable this behavior?
Best, Jan

**Comment by neilkuan** [comment]
okay, I will change `--eff-email` to `--no-eff-email`.
