### ISSUE TITLE
Possibility to upload certificates to S3 bucket top level

### ISSUE THREAD

**Issue by jpxd** [neilkuan/cdk-certbot-dns-route53#102]
Currently, the key files are uploaded to S3 in a directory with the current date. It would be great, if this would be optional and the files (fullchain, privkey) could just be updated in place at the top level in the S3 bucket. This way depending instances could just fetch the up-to-date keys from the same location every time.

**Comment by neilkuan** [comment]
Hi @jpxd , thanks for feedback.
so you want the optional to remove the directory with the current date. 
`aws s3 sync /tmp/live/ s3://${BUCKET_NAME}/${TODAY}/` to `aws s3 sync /tmp/live/ s3://${BUCKET_NAME}/${CUSTOM_PREFIX_DIRECTORY}/`. is that correct?!

**Comment by jpxd** [comment]
Hi @neilkuan, thank you very much for the quick changes and the release!
Looks like the new `customPrefixDirectory` exactly fits my needs! Will test today 👍

**Comment by neilkuan** [comment]
Hi @jpxd , in case you miss this.
Please read this https://github.com/neilkuan/cdk-certbot-dns-route53/blob/4aa4c5774188b651ed22b59cbc420445f1c72bc1/src/main.ts#L24-L31 , before you testing, thank you. ;)

**Comment by jpxd** [comment]
Works like a charm :) Thanks!
