### ISSUE TITLE
Option to run on deploy

### ISSUE THREAD

**Issue by thecarlo** [neilkuan/cdk-certbot-dns-route53#1056]
Great package.

I tried it out, but it doesn't seem to run on deploy and needs manual invocation.

Could you add a runOnDeploy option?

It is possible to add a schedule with 1 minute, but this has some obvious problems associated with it such as cost and rate limiting on certbot side.

**Comment by neilkuan** [comment]
Maybe you can use Custom Resource to invoke that after this constructs library been  created.
