### ISSUE TITLE
How to schedule  

### ISSUE THREAD

**Issue by DeanKamali** [neilkuan/cdk-certbot-dns-route53#246]
Hi there,  

is there is an option I need to add to create the renewal schedule? every 90 days? 

or do I need to create an event bridge and attach it to certbot lambda?

Thanks

**Comment by neilkuan** [comment]
You can define the schedule and define the customPrefixDirectory see #102.

**Comment by dkamali-mc** [comment]
Thank you, that worked flawlessly
